// autogenerated turbo fused MMA instance for TURBO8_0

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(256, 256, 32, 1, GGML_TYPE_TURBO8_0, GGML_TYPE_TURBO8_0);
