// autogenerated turbo fused MMA instance for TURBO8_0

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(128, 128, 8, 2, GGML_TYPE_TURBO8_0, GGML_TYPE_TURBO8_0);
