// autogenerated turbo fused MMA instance for TURBO2_0

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(256, 256, 8, 8, GGML_TYPE_TURBO2_0, GGML_TYPE_TURBO2_0);
