// autogenerated turbo fused MMA instance for asymmetric TURBO8_0 K / TURBO4_0 V (q6 sweet spot)

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(256, 256, 2, 8, GGML_TYPE_TURBO8_0, GGML_TYPE_TURBO4_0);
