// autogenerated turbo fused MMA instance for TURBO3_0

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(256, 256, 8, 1, GGML_TYPE_TURBO3_0, GGML_TYPE_TURBO3_0);
