// autogenerated turbo fused MMA instance for TURBO2_TCQ

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(128, 128, 2, 4, GGML_TYPE_TURBO2_TCQ, GGML_TYPE_TURBO2_TCQ);
