// autogenerated turbo fused MMA instance for TURBO3_TCQ

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(256, 256, 16, 2, GGML_TYPE_TURBO3_TCQ, GGML_TYPE_TURBO3_TCQ);
